# Generated by Django 4.2.9 on 2024-01-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SpotSavvy", "0003_activity_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
